[tool.briefcase]
project_name = "Toganvas"
bundle = "org.asheesh.toganvas"
version = "0.0.1"
url = "https://toganvas.asheesh.org/toganvas"
license = "MIT license"
author = 'Asheesh Laroia'
author_email = "asheesh@asheesh.org"

[tool.briefcase.app.toganvas]
formal_name = "Toganvas"
description = "Toga canvas line"
icon = "src/toganvas/resources/toganvas"
sources = ['src/toganvas']
requires = []


[tool.briefcase.app.toganvas.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.toganvas.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.toganvas.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.toganvas.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.toganvas.android]
requires = [
    '../../rubicon-java',
    '../../toga/src/core',
    '../../toga/src/android',
]
template = "../../briefcase-android-gradle-template"
